// Default messages and Typography

export const MESSAGES = {
  GENERAL_ERROR: "Internal Server Error",
  CONTACTS: {
    EXPORT_CONTACTS: "Are you sure you want to export these Contacts?",
    EXPORT_SINGLE_CONTACTS: "Are you sure you want to export this Contact?",
    DELETE_CONTACTS: "Are you sure you want to delete these Contacts?",
    DELETE_SINGLE_CONTACTS: "Are you sure you want to delete this Contact?",
    SEARCH_PLACE_HOLDER: "Search by name, company, address, phone, or email",
    END_DATE_REQUIRED: "Please select the end date.",
    FILTERS_REQUIRED: "Please select any filters.",
    SINGLE_EXPORT_HEADER: "Export",
    MULTI_EXPORT_HEADER: "Export list",
    SINGLE_DELETE_HEADER: "Delete",
    MULTI_DELETE_HEADER: "Delete list",
    CLEAR_FILTER_BTN_TEXT: "Clear Filters",
    CREATE_BTN_TEXT: "Create",
    EXPORT_BTN_TEXT: "Export",
    IMPORT_BTN_TEXT: "Import",
    DELETE_BTN_TEXT: "Delete",
    EDIT_BTN_TEXT: "Edit",
    SAVE_BTN_TEXT: "Save",
    EXPORT_MESSAGE: `You'll receive a confirmation email when the export is completed.`,
    DELETE_MESSAGE: `You'll receive a confirmation email when the delete is completed.`,
    CONTACT_DETAIL_TITLE: "Contact Details",
    CONTACT_BACK_ARROW: "Contacts",
    SELECT_ALL_ITEMS: "Select All",
    SELECT_VISIBLE_ITEMS: "Select Visible",
    SELECT_NONE: "Select None",
    EVENTS_LOGS: {
      TITLE: "Event Log",
      DUMMY_DATA: {
        ADDRESS_1_LABEL: "605 Abdul Haque Rd, Block H-3 Block H 3 Phase 2.",
        EVENT_1: " Created",
        DATE_1: "Nov 15, 2023 06:39:39 AM",
        ADDRESS_2_LABEL: "605 Abdul Haque Rd, Block H-3 Block H 3 Phase 2.",
        EVENT_2: " Updated",
        DATE_2: "Nov 15, 2023 09:39:39 AM",
      },
    },
    NO_CONTACTS_SCREEN: {
      TITLE: "You have no Contacts in your database",
      CREATE_CONTACT_BUTTON: "Create New Contact",
      IMPORT_BTN_TEXT: "Import Contacts",
    },
    ADVANCE_FILTERS: {
      HEADING: "Filters",
      SEARCH_TAG: "Search or Create a Tag",
      ADDRESS_STATUS: "Address Status",
      MAILED_STATUS: "Last Mailed Status",
      MAILED_DATE: "Last Mailed Date",
      CREATED_DATE: "Created Date",
      TAGS_LABEL: "Tags",
      CANCEL_BUTTON: "Clear",
      SUBMIT_BUTTON: "Apply",
    },
    DELETE: {
      TITLE: "Delete Contact",
      HEADING: "Are you sure you want to delete this contact?",
      MESSAGE:
        "This contact will be deleted from your Contacts database but will still be included in associated mailing campaigns.",
      CANCEL_BUTTON: "No",
      SUBMIT_BUTTON: "Yes",
    },
    IMPORT: {
      TITLE: "Import Contacts",
      UPLOAD_FILE: {
        TITLE: "Upload a File",
        DRAG_TEXT: " or drag and drop",
        FILE_TYPE: "CSV Files only",
        REQUIRED: "*File upload is required",
        REPLACE: "Please remove the current file to add new one",
        EMPTY_FILE: "Empty file is not allowed, please upload another one",
        INVALID_FILE: "File type must be CSV.",
      },
      DOWNLOAD: "Download",
      SAMPLE_FILE: " our sample CSV file here.",
      SMARTY_VALIDATIONS: {
        REQUIRED: "*",
        VALID_CONTACTS: " Contacts will be imported",
        VALID_CONTACT: " Contact will be imported",
        MISSING_CONTACT: " contact will be skipped due to missing information",
        MISSING_CONTACTS:
          " contacts will be skipped due to missing information",
        DUPLICATES_CONTACT: " contact will be skipped due to duplicates",
        DUPLICATES_CONTACTS: " contacts will be skipped due to duplicates",
      },
      ACTIONS: {
        SUCCESS_TITLE: "Contacts are Importing",
        SUCCESS_MESSAGE: " Contacts will be imported",
        SUCCESS_DESCRIPTION:
          "You will receive an email when your contacts have been imported into your database.",
        CANCEL_DESCRIPTION: "You will lose your changes after canceling.",
        CANCEL_TITLE: "Confirm Cancel Import",
        CANCEL_MESSAGE: "Are you sure you want to cancel this Import?",
        DONE_TEXT: "OK",
        BACK_TEXT: "Go Back",
        CANCEL_TEXT: "Cancel Import",
      },
      CONTACTS_MAPPING: {
        TITLE: "Map your CSV file",
        MATCH_LABEL: "Match",
        OLC_LABEL: "OLC Fields",
        CSV_LABEL: "CSV Columns",
        SAMPLE_LABEL: "Sample Data",
        REQUIRED: "*",
        REQUIRED_TEXT: " is required",
        SUBMIT_BUTTON: "Process CSV",
        CANCEL_BUTTON: "Cancel",
      },
      CANCEL_BUTTON: "Cancel",
      SUBMIT_BUTTON: "Import",
    },
    CREATE: {
      TITLE: "Create Contact",
      FIRST_NAME_LABEL: "First Name",
      LAST_NAME_LABEL: "Last Name",
      COMPANY_LABEL: "Company",
      ADDRESS_1_LABEL: "Address Line 1*",
      ADDRESS_2_LABEL: "Address Line 2",
      PHONE_VALIDATION: "Phone number is not valid",
      CITY_LABEL: "City*",
      STATE_LABEL: "State*",
      ZIP_LABEL: "Zip Code*",
      PHONE_LABEL: "Phone Number",
      EMAIL_LABEL: "Email Address",
      TAGS_LABEL: "Tags",
      TAGS_PLACEHOLDER: "Search a Tag",
      CREATE_SEARCH_TAGS_PLACEHOLDER: "Search or Create a Tag",
      FIRST_NAME_OR_COMPANY_REQUIRED:
        "The first name or company name field is required",
      COMPANY_MAX_LENGTH: "Company name must be less than 100 characters",
      ADDRESS_1__REQUIRED: "Address Line 1 is required",
      CITY_REQUIRED: "City name is required",
      STATE_REQUIRED: "State name is required",
      ZIP_REQUIRED: "Zip code is required",
      SUBMIT_BUTTON: "Create",
      CANCEL_BUTTON: "Cancel",
    },
    EDIT: {
      FIRST_NAME_OR_COMPANY: "The first name or company name field is required",
      FIRST_NAME_LABEL: "First Name",
      LAST_NAME_LABEL: "Last Name",
      COMPANY_LABEL: "Company",
      COMPANY_MAX_LENGTH: "Company name must be less than 100 characters",
      ADDRESS_1_LABEL: "Address Line 1",
      ADDRESS_2_LABEL: "Address Line 2",
      CITY_LABEL: "City",
      STATE_LABEL: "State",
      ZIP_LABEL: "Zip Code",
      PHONE_LABEL: "Phone Number",
      TAGS_LABEL: "Tags",
      EMAIL_LABEL: "Email Address",
      ADDRESS_STATUS: "Address Status",
      TOTAL_MAILED: "Total Mailed",
      LAST_MAILED_STATUS: "Last Mailed Status",
      LAST_MAILED_DATE: "Last Mailed Date",
      DATE_LABEL: "Date Created",
      PROPERTY_ADDRESS: "Property Address",
      PROPERTY_CITY: "Property City",
      PROPERTY_STATE: "Property State",
      PROPERTY_ZIP: "Property Zip Code",
    },
  },
  TEMPLATE: {
    SEARCH_PLACE_HOLDER: "Search by template name or template ID",
    NAME_REQUIRED: "Template Name is required",
    TYPE_REQUIRED: "Template Type is required",
    PRODUCT_TYPE_REQUIRED: "Product Type is required",
    ENVELOPE_TYPE_REQUIRED: "*Envelope Type is required",
    POSTCARD_SIZE_REQUIRED: "Postcard Size is required",
    NAME_LESS_50: "Template Name should be less than or equal to 50 characters",
    LIMIT_MODAL: {
      TITLE: "Limit Reached",
      HEADING: "You've reached your template limit",
      SUB_HEADING: "Please Upgrade your subscription to add more templates",
      CANCEL_BUTTON: "Cancel",
      SUBMIT_BUTTON: "View Plans",
    },
    DELETE: {
      TITLE: "Delete Template",
      HEADING: "Are you sure you want to delete this Template?",
      PARAGRAPH:
        "This template will be deleted from your Templates list but will still be included in associated orders.",
    },
    SAVE: {
      TITLE: "Confirm Save Template",
      HEADING: "Are you sure you want to save this template?",
      PARAGRAPH:
        "The updates provided will be used right away for any orders referencing this template.",
      CANCEL_BUTTON: "Cancel",
      SUBMIT_BUTTON: "Save"
    },
    CANCEL: {
      TITLE: "Confirm Cancel Template",
      HEADING: "Are you sure you want to cancel this Template?",
      PARAGRAPH: "You will lose your changes after canceling.",
      BACK_BUTTON: "Go Back",
      CANCEL_BUTTON: "Cancel",
    },
    DESIGN_YOUR_OWN: {
      TITLE: "Confirm",
      HEADING: "Are you sure you want to discard these changes?",
      PARAGRAPH:
        "You will lose your changes. Please save your changes or click ok to proceed.",
    },
    SELECT_TEMPLATE: {
      TITLE: "Confirm",
      HEADING:
        "Are you sure you want to change current template with this one?",
      PARAGRAPH:
        "You will lose your changes. Please save your changes or click ok to proceed.",
      SUBMIT_BUTTON: "OK",
      CANCEL_BUTTON: "Cancel",
    },
    CANCEL_BUTTON: "Cancel",
    SUBMIT_BUTTON: "Save"
  },
  ORDERS: {
    SEARCH_PLACE_HOLDER: "Search by order ID",
    CLEAR_FILTER_BTN_TEXT: "Clear Filters",
    CANCEL_ORDER_BTN_TEXT: "Cancel Order",
    PAY_AND_PROCESS_BTN_TEXT: "Pay and Process",
    END_DATE_REQUIRED: "Please select the end date.",
    FILTERS_REQUIRED: "Please select any filters.",
    NO_ORDERS_SCREEN: {
      TITLE: "You have no Orders in your database",
      CREATE_ORDER_BUTTON: "Create New Order",
    },
    ADVANCE_FILTERS: {
      HEADING: "Filters",
      PRODUCT_TYPE_LABEL: "Product type",
      SOURCE_LABEL: "Source",
      ORDER_STATUS_LABEL: "Order Status",
      PAYMENT_STATUS_LABEL: "Payment Status",
      CREATED_DATE_LABEL: "Created Date",
      SCHEDULED_DATE_LABEL: "Scheduled Date",
      CANCEL_BUTTON: "Clear",
      SUBMIT_BUTTON: "Apply",
    },
    CREATE: {
      TITLE: "Create New Order",
      DELIVERABLES_REQUIRED:
        "You should have at least 1 deliverable contact before submitting the order.",
      TEMPLATE_LABEL: "Select Template*",
      TEMPLATE_REQUIRED: "Template is required",
      PRODUCT_TYPE_LABEL: "Product Type: ",
      ENVELOPE_TYPE_LABEL: "Envelope Type: ",
      POSTCARD_SIZE_LABEL: "Postcard Size: ",
      POSTAGE_TYPE_LABEL: "Postage Type*",
      POSTAGE_TYPE_REQUIRED: "Postage Type is required",
      ENVELOPE_STYLE_LABEL: "Envelope Style* ",
      ENVELOPE_STYLE_REQUIRED: "Envelope Style is  required",
      VIEW_PROOF_LABEL: "Download Proof",
      HTML_TEMPLATE_LABEL:
        "*HTML Templates cannot display an image. Click to Download proof.",
      CONTACT_COUNT_TEXT: " Contact Selected ",
      CONTACTS_COUNT_TEXT: " Contacts Selected ",
      CONTACT_REQUIRED: "Contact is required",
      RETURN_ADDRESS_TITLE: "Return Address*",
      RETURN_ADDRESS_REQUIRED: "This field is required",
      DATE_LABEL: "Scheduled Date* ",
      DATE_REQUIRED: "This field is required",
      DELIVERY_DATE: "Mail Date: ",
      CANCEL_BUTTON: "Cancel",
      NEXT_BUTTON: "Next",
      SUBMIT_BUTTON: "Submit Order",
      LEARN_TITLE: "Learn More",
      BACK_BUTTON: "Back",
      CONTACTS: {
        CONTACT_LABEL: "Select Contacts*",
        SINGLE: "Single Contact",
        MULTIPLE: "Multiple Contacts",
        UPLOAD: "Upload Contacts",
        CREATE: "Create New Contact",
        SUBMIT_BUTTON: "Create",
        CANCEL_BUTTON: "Cancel",
      },
      REVIEW: {
        COST_HEADING: "Estimated Cost ",
        COST_TITLE:
          "Cost is dependent on merge strictness and the deliverability of your contacts when the order is processed. ",
        HEADING: "Please Inspect your order thoroughly for the following:",
        DELIVERABLE_TITLE: " deliverable contact",
        DELIVERABLES_TITLE: " deliverable contacts",
        MAILER_TITLE: " per mailer",
        PROOF_TITLE: "Proof is displaying all content correctly",
        SPELLING_TITLE: "There are no spelling errors",
        VARIABLE_TITLE:
          "All variable fields in my template are correct and merged with correct contact data.",
        REQUIRED: "All are required",
        HTML_LABEL: "Download Proof here...",
        PROOF_LABEL: "Download Proof",
        DESCRIPTION:
          "Orders are charged on their Scheduled Date, not when they are submitted. Orders are eligible to be canceled up to their Scheduled Date.",
      },
      SUBMIT_MODAL: {
        TITLE: "Order Submitted",
        CANCEL_TITLE: "Confirm Cancel Order?",
        HEADING: "Your Order has been placed Successfully",
        CANCEL_HEADING: "Are you sure you want to cancel this Order?",
        DESCRIPTION:
          "You will receive an email when your contacts have been imported into your database.",
        CANCEL_DESCRIPTION: "You will lose your changes after canceling.",
        BACK_BUTTON: "Go Back",
        SUBMIT_BUTTON: "OK",
        CANCEL_BUTTON: "Cancel Order",
      },
    },
    DETAIL: {
      OVERVIEW: {
        NO_DATA: "No data",
        NO_DATA_ANALYTICS:
          "Analytics are updated when order is in Mailed status",
        MAILED: "Mailed",
        IN_TRANSIT: "In Transit",
        DELIVERED: "Delivered",
        RE_ROUTE: "Re-Routed",
        RETURNED_TO_SENDER: "Returned to Sender",
        SCANNED: "Scanned",
        NOT_SCANNED: "Not Scanned",
        DAY_ELAPSED: "Day Elapsed",
        CANCEL_ORDER_BUTTON: "Cancel Order",
        VIEW_PROOF_BUTTON: "Download Proof",
        TOTAL_CONTACTS: "Total Contacts",
        DELIVERABLES: "Deliverables",
        UNDELIVERABLES: "Undeliverables",
        TOTAL_COST: "Total Cost",
        ADD_FUND_AND_PROCESS_ORDER: "Add Funds & Process Order",
        PAY_AND_PROCESS_BUTTON: "Pay & Process Order",
        AMOUNT_NOT_ENOUGH_FOR_ORDER:
          "*Amount added to your wallet isn't enough for your order",
      },
      CONTACTS: {
        FILTER: {
          TITLE: "Filters",
          FILTER_REQUIRED: "Please select any filter",
          ADDRESS_STATUS: "Address Status",
          MAILED_STATUS: "Mailed Status",
          DELIVERED_DATE: "Delivered Date",
          CANCEL_BUTTON: "Clear",
          SUBMIT_BUTTON: "Apply",
        },
        REMOVE: {
          CONTACT: "Remove Contact",
          MODAL: {
            REMOVE_CONTACT: {
              SINGLE_REMOVE_HEADING: "Remove Contact?",
              MULTI_REMOVE_HEADING: "Remove Contacts?",
              REMOVE_CONTACTS:
                "Are you sure you want to remove these Contacts?",
              REMOVE_SINGLE_CONTACTS:
                "Are you sure you want to remove this Contact?",
              NOTE: `This action cannot be undone. Please proceed with caution.`,
            },
          },
        },
        TABLE: {
          SELECT_ALL_ITEMS: "Select All",
          SELECT_VISIBLE_ITEMS: "Select Visible",
          SELECT_NONE: "Select None",
          NO_RESULT: "No results with current filters.",
        },
        CLEAR_FILTERS: "Clear Filters",
      },
      MODALS: {
        CANCEL: {
          HEADING: "Cancel Order?",
          MESSAGE: "Are you sure you want to cancel this order?",
          MULTI_MESSAGE: "Are you sure you want to cancel these order?",
          SUCCESS_BUTTON: "Yes",
          SUB_MESSAGE:
            "This action cannot be undone. You will not be charged for this order",
          MULTI_SUB_MESSAGE:
            "This action cannot be undone. You will not be charged for these orders",
        },
        PAY_AND_PROCESS: {
          HEADING: "Process Order",
          MESSAGE: "Are you sure you want to proceed?",
          SUCCESS_BUTTON: "Process Order",
          SUB_MESSAGE:
            "Your order will be resubmitted and processed. Your order is scheduled for ",
          MULTI_SUB_MESSAGE:
            "Your orders will be resubmitted and processed. Your orders is scheduled for ",
        },
        ADD_FUNDS: {
          HEADING: "Insufficient Funds",
          MESSAGE: "Not enough fund in wallet",
          SUCCESS_BUTTON: "Add Funds",
          SUB_MESSAGE: "Please add funds before processing this order",
        },
      },
    },
  },
  SNACKBAR: {
    HEADING: "Notifications",
  },
} as const;
